### ISSUE TITLE
When a user changes the ownership of an existing parameter and sets the value of a contained ParameterValueSet the server returns an internal server error

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/COMET-WebServices-Community-Edition#145]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4 Web Services
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce
  - Create a Parameter as domain A
  - Edit parameter by popping details dialog, change owner to another domain and set value of manual value
  - server returns an internal server exception

### System Configuration
NA

- CDP4 Web Services version: Version 6.0.0-RC2
  - [x] PostrgreSQL: 12.x

**Comment by lxatrhea** [comment]
Solution: Throw Bad Request error instead of internal server error.
Change IME so that changing Owner also makes the ParameterValueSet readonly and does not send the ParameterValueSet change to the server, the same way it is already implemented for the Parameter's State and Option dependency settings.
